---
services:
  mariadb:
    image: "docker.io/mariadb"
    container_name: "mariadb"
    restart: "always"
    environment:
      MARIADB_DATABASE: "${MARIADB_DATABASE:?}"
      MARIADB_ROOT_PASSWORD: "${MARIADB_ROOT_PASSWORD-password}"
    volumes:
      - "mariadb:/var/lib/mysql"
    ports:
      - "3306:3306"

volumes:
  mariadb:
