---
services:
  adminer:
    image: "docker.io/trafex/php-nginx"
    container_name: "nginx-php"
    restart: "always"
    volumes:
      - "./www/html:/var/www/html:ro"
    ports:
      - "80:80"
    command: ["php", "-S", "0.0.0.0:8080", "-t", "/var/www/html"]
